### ISSUE TITLE
docker-compose 網路問題

### ISSUE THREAD

**Issue by ifurther** [i3thuan5/hok8-bu7#26]
會提示

`
Creating network "hok8-bu7_default" with the default driver
ERROR: Network nginx-bridge declared as external, but could not be found. Please create the network manually using `docker network create nginx-bridge` and try again.
`

**Comment by sih4sing5hong5** [comment]
Gún有用 [nginx-proxy](https://github.com/jwilder/nginx-proxy)，這是[Gún ê詳細設定](https://github.com/i3thuan5/TsuKi/blob/master/nginx-start#L1)

你若無需要，ē-tàng kā https://github.com/i3thuan5/hok8-bu7/blob/master/docker-compose.yml#L15 kah https://github.com/i3thuan5/hok8-bu7/blob/master/docker-compose.yml#L36-L38 提掉，加上 docker-compose.yml ê ports就好--ah
```
  gunicorn:
    ports:
    - 8000:8000
```
按呢 localhost:8000 應該就有--ah

**Comment by ifurther** [comment]
好喔，謝謝
